apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/ericlong07/shiny-app:database
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
            - name: PGDATA
              value: /var/lib/postgresql/data/pg_data
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: my-postgres-data
              mountPath: /var/lib/postgresql/data/slurm_data
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"  # Set the desired memory limit here
            requests:
              cpu: "0.5"
              memory: "512Mi"  # Set the desired memory request here
      volumes:
        - name: my-postgres-data
          emptyDir: {}
