apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Set the desired storage size here
  storageClassName: standard  # Change to your preferred storage class name, if applicable
