# For local testing purposes
version: '3.8'
services:
  postgres:
    image: postgres-container
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pg_data
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Mount the volume to /var/lib/postgresql/data

volumes:
  postgres-data:
